#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/3/21 16:07
# @Author  : Jedrek

# -*- coding:utf-8 -*-

import sys
import os
from win32com.client import Dispatch, constants, gencache


def doc2pdf(input_path, output_path):
    w = Dispatch("Word.Application")

    try:
        doc = w.Documents.Open(input_path, ReadOnly=1)
        doc.ExportAsFixedFormat(output_path, constants.wdExportFormatPDF,
                                Item=constants.wdExportDocumentWithMarkup,
                                CreateBookmarks=constants.wdExportCreateHeadingBookmarks)
        return 0
    except Exception:
        return 1
    finally:
        w.Quit(constants.wdDoNotSaveChanges)


def generate_support():
    # enable python COM support for Word 2007
    # this is generated by: makepy.py -i "Microsoft Word 12.0 Object Library"
    gencache.EnsureModule('{00020905-0000-0000-C000-000000000046}', 0, 8, 4)


def main():
    if len(sys.argv) == 2:
        input_path = sys.argv[1]
        output_path = os.path.splitext(input_path)[0] + '.pdf'
    elif len(sys.argv) == 3:
        input_path = sys.argv[1]
        output_path = sys.argv[2]
    else:
        input_path = u'C:\\Users\\wangjie22438\\Desktop\\testdoc.doc'  # word文档的名称
        output_path = u'C:\\Users\\wangjie22438\\Desktop\\BA06007013.pdf'  # pdf文档的名称
    if not os.path.isabs(input_path):
        input_path = os.path.abspath(input_path)
    if not os.path.isabs(output_path):
        output_path = os.path.abspath(output_path)
    try:
        generate_support()
        rc = doc2pdf(input_path, output_path)
        return rc
    except:
        return -1


if __name__ == '__main__':
    rc = main()
    if rc:
        sys.exit(rc)
    sys.exit(0)
